"""
Epistemic Alignment — Validates LLM-generated claims against retrieved evidence

Implements:
- Semantic overlap detection
- Contradiction detection
- Usage tracking for memory adaptation
- Alignment classification (M5/M6)
"""

import re
from dataclasses import dataclass
from typing import List, Tuple, Dict, Optional

from grilo_falante.backend.services.llm import LLMMessage, get_llm_service


NEGATION_MARKERS = {
    "not", "no", "never", "none", "without", "isn't", "aren't", "wasn't", "weren't",
    "doesn't", "don't", "didn't", "cannot", "can't", "won't",
    "não", "nao", "nunca", "nenhum", "nenhuma", "sem",
}

STOPWORDS = {
    "the", "a", "an", "of", "in", "on", "at", "for", "to", "and", "or", "is",
    "are", "was", "were", "be", "been", "being", "do", "does", "did", "with",
    "by", "as", "that", "this", "these", "those", "it", "its",
    "o", "a", "os", "as", "de", "da", "do", "das", "dos", "em", "no", "na",
    "nos", "nas", "por", "para", "e", "ou", "é", "foi", "ser", "com", "um",
    "uma", "uns", "umas", "isto", "isso", "aquele", "aquela",
}


def _normalize_text(text: str) -> str:
    text = (text or "").lower().strip()
    text = re.sub(r"[^\w\sà-ÿ]", " ", text, flags=re.UNICODE)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _tokenize(text: str) -> List[str]:
    normalized = _normalize_text(text)
    if not normalized:
        return []
    return [tok for tok in normalized.split() if tok]


def _content_tokens(text: str) -> List[str]:
    return [tok for tok in _tokenize(text) if tok not in STOPWORDS and len(tok) > 2]


def _has_negation(text: str) -> bool:
    tokens = set(_tokenize(text))
    return any(tok in tokens for tok in NEGATION_MARKERS)


def _jaccard(tokens_a: List[str], tokens_b: List[str]) -> float:
    set_a = set(tokens_a)
    set_b = set(tokens_b)
    if not set_a or not set_b:
        return 0.0
    return len(set_a & set_b) / len(set_a | set_b)


def _containment_score(tokens_a: List[str], tokens_b: List[str]) -> float:
    set_a = set(tokens_a)
    set_b = set(tokens_b)
    if not set_a or not set_b:
        return 0.0
    return len(set_a & set_b) / min(len(set_a), len(set_b))


def _semantic_overlap(claim_text: str, evidence_text: str) -> float:
    claim_tokens = _content_tokens(claim_text)
    evidence_tokens = _content_tokens(evidence_text)
    if not claim_tokens or not evidence_tokens:
        return 0.0
    return (0.4 * _jaccard(claim_tokens, evidence_tokens) +
            0.6 * _containment_score(claim_tokens, evidence_tokens))


def classify_claim_evidence_pair(
    claim_text: str,
    evidence_text: str,
    threshold: float = 0.55,
) -> Tuple[str, float]:
    """
    Classify the relationship between a claim and a piece of evidence.

    Returns:
        tuple: (relation: "supported" | "contradicted" | "unrelated", score: float)
    """
    score = _semantic_overlap(claim_text, evidence_text)
    if score < threshold:
        return "unrelated", score

    if _has_negation(claim_text) != _has_negation(evidence_text):
        return "contradicted", score

    return "supported", score


@dataclass
class AlignedClaim:
    text: str
    status: str
    matched_evidence: Optional[str]
    score: float
    evidence_id: Optional[int] = None


@dataclass
class AlignmentResult:
    type: str
    claims: List[AlignedClaim]
    support: int
    contradictions: int
    unverified: int
    note: str = ""


class EpistemicAlignment:
    """
    Aligns LLM-generated claims against retrieved evidence.
    Used to validate that generated content is grounded in known evidence.
    """

    def __init__(self, threshold: float = 0.55):
        self.threshold = threshold

    def align(
        self,
        llm_claims: List[str],
        evidence_claims: List[dict],
    ) -> AlignmentResult:
        """
        Align LLM claims against evidence claims.

        Args:
            llm_claims: List of claim texts generated by LLM
            evidence_claims: List of evidence dicts with 'text', 'id', 'score' keys

        Returns:
            AlignmentResult with classification
        """
        if not llm_claims:
            return AlignmentResult(
                type="M5_unverified",
                claims=[],
                support=0,
                contradictions=0,
                unverified=0,
                note="no_llm_claims",
            )

        if not evidence_claims:
            return AlignmentResult(
                type="M5_unverified",
                claims=[
                    AlignedClaim(text=c, status="unverified", matched_evidence=None, score=0.0)
                    for c in llm_claims
                ],
                support=0,
                contradictions=0,
                unverified=len(llm_claims),
                note="no_evidence",
            )

        aligned: List[AlignedClaim] = []

        for claim_text in llm_claims:
            best_relation = "unverified"
            best_score = 0.0
            best_evidence_text = None
            best_evidence_id = None

            for evidence in evidence_claims:
                evidence_text = str(evidence.get("text", "")).strip()
                evidence_id = evidence.get("id")

                if not evidence_text:
                    continue

                relation, score = classify_claim_evidence_pair(
                    claim_text, evidence_text, self.threshold
                )

                if score > best_score:
                    best_score = score
                    best_evidence_text = evidence_text
                    best_evidence_id = evidence_id

                    if relation == "supported":
                        best_relation = "supported"
                    elif relation == "contradicted":
                        best_relation = "contradicted"

            aligned.append(AlignedClaim(
                text=claim_text,
                status=best_relation,
                matched_evidence=best_evidence_text,
                score=round(best_score, 3),
                evidence_id=best_evidence_id,
            ))

        supported = sum(1 for a in aligned if a.status == "supported")
        contradicted = sum(1 for a in aligned if a.status == "contradicted")

        if not aligned:
            alignment_type = "M5_unverified"
        elif supported == len(aligned):
            alignment_type = "M6_supported"
        elif contradicted > 0:
            alignment_type = "M6_conflicted"
        elif supported > 0:
            alignment_type = "M6_partial"
        else:
            alignment_type = "M5_unverified"

        return AlignmentResult(
            type=alignment_type,
            claims=aligned,
            support=supported,
            contradictions=contradicted,
            unverified=len(aligned) - supported - contradicted,
        )

    async def align_with_llm(
        self,
        raw_answer: str,
        evidence_claims: List[dict],
        llm_provider: Optional[str] = None,
    ) -> AlignmentResult:
        """
        Extract claims from LLM answer and align them.

        Uses the LLM service to extract claims from raw text.
        """
        llm = get_llm_service(llm_provider)

        extraction_prompt = (
            "Extract the key factual claims from this text. "
            "Return a JSON list of claim strings.\n\n" + raw_answer
        )

        messages = [
            LLMMessage(role="system", content="You extract claims. Return only a JSON list of strings."),
            LLMMessage(role="user", content=extraction_prompt),
        ]

        response = await llm.chat(messages)

        import json
        try:
            llm_claims = json.loads(response.content)
            if not isinstance(llm_claims, list):
                llm_claims = []
        except Exception:
            llm_claims = [line.strip() for line in response.content.split("\n") if line.strip()]

        return self.align(llm_claims, evidence_claims)
