"""Admin models."""

from grilo_admin.models.user import (
    User,
    UserCreate,
    UserUpdate,
    UserLogin,
    UserRole,
    Token,
    TokenData,
)

from grilo_admin.models.repository import (
    Repository,
    RepositoryCreate,
    RepositoryUpdate,
    RepositoryType,
    RepositoryStatus,
    Chunk,
    Document,
    FAQItem,
    IngestionRequest,
    IngestionResult,
    SearchRequest,
    SearchResult,
)

from grilo_admin.models.article import (
    Article,
    ArticleCreate,
    ArticleUpdate,
    ArticlePhase,
    ArticleStatus,
    ArticleType,
    ShadowDocument,
    ShadowDocumentCreate,
    ShadowDocumentInDB,
    SourceType,
    ArticleClaim,
    ArticleClaimCreate,
    Falacia,
    FalaciaCreate,
    FalaciaType,
    FalaciaSeverity,
    FalaciaStatus,
    Gap,
    GapCreate,
    GapStatus,
    FAQFromGap,
    FAQFromGapCreate,
    ValidationStatus,
    ClaimRole,
    GMIFLevel,
    WikiView,
    LearningResult,
    ValidationQueueItem,
)

from grilo_admin.models.ilha import (
    ILHA,
    ILHACreate,
    ILHAUpdate,
    ILHAFromConversation,
    Participant,
    Pedra,
    InteractionType,
    LogbookEntry,
    ConversationMessage,
)

__all__ = [
    # User models
    "User",
    "UserCreate",
    "UserUpdate",
    "UserLogin",
    "UserRole",
    "Token",
    "TokenData",
    # Repository models
    "Repository",
    "RepositoryCreate",
    "RepositoryUpdate",
    "RepositoryType",
    "RepositoryStatus",
    "Chunk",
    "Document",
    "FAQItem",
    "IngestionRequest",
    "IngestionResult",
    "SearchRequest",
    "SearchResult",
    # Article models
    "Article",
    "ArticleCreate",
    "ArticleUpdate",
    "ArticlePhase",
    "ArticleStatus",
    "ArticleType",
    "ShadowDocument",
    "ShadowDocumentCreate",
    "ShadowDocumentInDB",
    "SourceType",
    "ArticleClaim",
    "ArticleClaimCreate",
    "Falacia",
    "FalaciaCreate",
    "FalaciaType",
    "FalaciaSeverity",
    "FalaciaStatus",
    "Gap",
    "GapCreate",
    "GapStatus",
    "FAQFromGap",
    "FAQFromGapCreate",
    "ValidationStatus",
    "ClaimRole",
    "GMIFLevel",
    "WikiView",
    "LearningResult",
    "ValidationQueueItem",
    # ILHA models
    "ILHA",
    "ILHACreate",
    "ILHAUpdate",
    "ILHAFromConversation",
    "Participant",
    "Pedra",
    "InteractionType",
    "LogbookEntry",
    "ConversationMessage",
]
